-- Zara Kitchen: Real Menu Items (migrated from lib/menuData.ts)
-- Run this in Supabase SQL Editor, AFTER menu_items_table.sql

insert into menu_items (category, name, description, price, image_url, is_available, is_spicy, is_vegetarian, is_featured_hero, display_order) values
('Healthy Breakfast', 'Granola Bowl', 'Muesli, plain yoghurt, assorted berries, chia seeds for garnish', 30.00, '/images/menu/healthy-breakfast/cereak-bowl.jpg', true, false, false, false, 0),
('Healthy Breakfast', 'Cereal Bowl', 'Corn flakes, all bran flakes, oats porridge', 25.00, '/images/menu/healthy-breakfast/fruit-salad.jpg', true, false, false, false, 1),
('Healthy Breakfast', 'Fruit Salad', 'Assorted sliced fruits', 35.00, '/images/menu/healthy-breakfast/granola-bowl.jpg', true, false, true, false, 2),
('Hot Breakfast', 'Zara Full Breakfast', '2 fried eggs, bacon, grilled tomato, sausages, mushroom, hashbrown', 35.00, '/images/menu/hot-breakfast/avocago-bacon-egg.jpg', true, false, false, false, 3),
('Hot Breakfast', 'Avocado, Bacon & Egg Toast', 'Health bread, smashed avocado, bacon, poached egg', 45.00, '/images/menu/hot-breakfast/bacon-benedict.jpg', true, false, false, false, 4),
('Hot Breakfast', 'Omelette', 'Assorted fillings', 40.00, '/images/menu/hot-breakfast/omlette.jpg', true, false, false, false, 5),
('Hot Breakfast', 'Bacon Benedict', 'English muffin, smoked salmon, poached egg, hollandaise sauce', 35.00, '/images/menu/hot-breakfast/zara-full-breakfast1.jpg', true, false, false, false, 6),
('On the Bakery', 'Assorted Muffins', 'Chocolate, vanilla, berry', 25.00, '/images/menu/on-the-bakery/assorted-muffins.jpg', true, false, false, false, 7),
('On the Bakery', 'Pancakes', 'Garnished with syrup and whipped cream', 15.00, '/images/menu/on-the-bakery/croissant.jpg', true, false, false, false, 8),
('On the Bakery', 'Waffles', 'Garnished with chocolate sauce and honey', 20.00, '/images/menu/on-the-bakery/pan-cake.jpg', true, false, false, false, 9),
('On the Bakery', 'Scones', 'Served with a side of jam and cheese', 15.00, '/images/menu/on-the-bakery/scones.jpg', true, false, false, false, 10),
('On the Bakery', 'Croissants', 'Plain, cheese & ham, or cheese & tomato', 15.00, '/images/menu/on-the-bakery/waffles.jpg', true, false, false, false, 11),
('Appetisers', 'Fried Calamari', 'With aioli & lemon herb', 45.00, '/images/menu/appetisers/fried-calamari.jpg', true, false, false, false, 12),
('Appetisers', 'Chicken Wings', 'Soy glazed crispy chicken wings, topped with sesame seeds & coriander', 55.00, '/images/menu/appetisers/chicken-wings.jpg', true, false, false, false, 13),
('Appetisers', 'Prawns', 'Flash fried in chili, garlic, butter, lemon & parsley', 35.00, '/images/menu/appetisers/prawns.jpg', true, true, false, false, 14),
('Appetisers', 'Kelewele', 'Spicy fried plantain', 35.00, '/images/menu/appetisers/kelewele.jpg', true, true, false, false, 15),
('Appetisers', 'Grilled Spicy Guinea Fowl', 'Spring onions, red chili, kebab powder', 50.00, '/images/menu/appetisers/guinea-fowl.jpg', true, true, false, false, 16),
('Appetisers', 'Spicy Pork Ribs', 'Spring onions, red chili, kebab powder', 60.00, '/images/menu/appetisers/spicy-pork-ribs.jpg', true, true, false, false, 17),
('Appetisers', 'Vegetable Spring Rolls', 'Onions, cabbage, carrots, chef''s special spice', 45.00, '/images/menu/appetisers/vegetable-spring-rolls.jpg', true, false, true, false, 18),
('Salads', 'Asian Calamari Salad', 'Grilled or fried calamari, pickled ginger, tomato, avocado, cucumber, greens & spring onion with a soy miso dressing', 35.00, '/images/menu/salads/asian-salad.jpg', true, false, true, false, 19),
('Salads', 'Caesar Salad', 'Crisp romaine lettuce with creamy Caesar dressing, anchovies, grilled chicken, bacon, Parmesan cheese', 45.00, '/images/menu/salads/avacado-salad.jpg', true, false, false, false, 20),
('Salads', 'Avocado Salad', 'Lettuce, cucumber, carrot, tomato, avocado, onions, chopped parsley, chopped chilli, honey, olive oil', 25.00, '/images/menu/salads/ceaser-salad.jpg', true, true, true, false, 21),
('Salads', 'Green Salad', 'Lettuce, green pepper, cucumber, spring onion, green beans, green olives, olive oil', 40.00, '/images/menu/salads/green-salad.jpg', true, false, true, false, 22),
('Salads', 'Zara Ghanaian Salad', 'Lettuce, cabbage, tuna flakes, baked beans, tomatoes, onion, egg, chicken, chef''s special sauce', 30.00, '/images/menu/salads/zara-salad.jpg', true, false, false, false, 23),
('Light Meals', 'Club Sandwich', 'Brown or white toast, lettuce, tomato, cheese, ham, sauce -- served with fries or salad', 35.00, '/images/menu/light-meals/bacon-avo.jpg', true, false, false, false, 24),
('Light Meals', 'Zara Chic', 'Brown or white toast, lettuce, chicken mayo, cheese, sauce -- served with fries or salad', 35.00, '/images/menu/light-meals/beef-wrap.jpg', true, false, false, false, 25),
('Light Meals', 'Missy Tuna', 'Brown or white toast, lettuce, tuna, cheese, sauce -- served with fries or salad', 40.00, '/images/menu/light-meals/boss-lady.jpg', true, false, false, false, 26),
('Light Meals', 'Boss Lady', 'Brown or white toast, lettuce, fried egg, bacon, tomato, cheese, sauce -- served with fries or salad', 50.00, '/images/menu/light-meals/chicken-burger.jpg', true, false, false, false, 27),
('Light Meals', 'Bacon Avo', 'Baguette bread, bacon, avocado, cucumber, arugula, baby spinach, radish, sunflower tomatoes, creamy cheese', 35.00, '/images/menu/light-meals/chicken-wrap.jpg', true, false, false, false, 28),
('Light Meals', 'Chicken Wrap', 'Tortilla, lettuce, green pepper, tomato, shredded chicken, sauce -- served with fries or salad', 45.00, '/images/menu/light-meals/coument-beef.jpg', true, false, false, false, 29),
('Light Meals', 'Beef Wrap', 'Tortilla, lettuce, green pepper, caramelized onion, tomato, shredded beef, sauce -- served with fries or salad', 45.00, '/images/menu/light-meals/miss-tuna.jpg', true, false, false, false, 30),
('Light Meals', 'Chicken Burger', 'Bun, lettuce, chicken fillet, gherkins, tomato, caramelized onion, cheese -- served with fries or salad', 40.00, '/images/menu/light-meals/sandwitch.jpg', true, false, false, false, 31),
('Light Meals', 'Gourmet Beef Burger', 'Bun, lettuce, beef patty, gherkins, tomato, crispy bacon, caramelized onion, cheese, sauce -- served with fries or salad', 45.00, '/images/menu/light-meals/zara-chic.jpg', true, false, false, false, 32),
('On the Grill', 'Beef Tenderloin 250g', 'Served with a side of salad, mediterranean vegetables, mashed potatoes or French fries', 95.00, '/images/menu/on-the-grill/bbq-chicken.jpg', true, false, false, false, 33),
('On the Grill', 'Surf & Turf', '200g beef steak, 5 queen prawns, served with French fries', 95.00, '/images/menu/on-the-grill/beef-tenderliom.jpg', true, false, false, false, 34),
('On the Grill', 'BBQ Chicken & Rib Combo', 'Quarter leg chicken, 200g pork ribs, served with French fries', 105.00, '/images/menu/on-the-grill/grilled-salmon.jpg', true, false, false, false, 35),
('On the Grill', 'Lamb Chops 250g', 'Served with a side of salad, mediterranean vegetables, mash potatoes or French fries', 140.00, '/images/menu/on-the-grill/lamb-chop.jpg', true, false, false, false, 36),
('On the Grill', 'Grilled Salmon', 'Grilled salmon in teriyaki sauce, served with mashed potatoes or mediterranean vegetables', 120.00, '/images/menu/on-the-grill/surf-turf.jpg', true, false, false, false, 37),
('Pastas', 'Grilled Creamy Chicken Pesto Pasta', 'Grilled chicken, mushrooms in a creamy basil pesto sauce, penne pasta and Grana Padano shavings', 65.00, '/images/menu/pastas/fettucini-polo.jpg', true, false, false, false, 38),
('Pastas', 'Seafood Pasta', 'Hake, mussels, prawns and calamari in a creamy prawn and lemongrass sauce, served with fettuccine', 75.00, '/images/menu/pastas/grilled-creamy.jpg', true, false, false, false, 39),
('Pastas', 'Mushroom Pasta (V)', 'Medley of mixed mushrooms gently simmered in a creamy Parmesan sauce, served with penne pasta', 70.00, '/images/menu/pastas/mac-cheease.jpg', true, false, true, false, 40),
('Pastas', 'Mac & Cheese', 'Creamy cheese sauce, penne pasta and melted cheddar cheese', 65.00, '/images/menu/pastas/mushroom.jpg', true, false, true, false, 41),
('Pastas', 'Spaghetti Bolognaise', 'Napolitano sauce, beef mince and spaghetti pasta', 80.00, '/images/menu/pastas/penne-arabtiana.jpg', true, false, false, false, 42),
('Pastas', 'Penne Arrabbiata', 'Spicy pomodoro, olives, parmesan cheese', 75.00, '/images/menu/pastas/sea-food.jpg', true, true, false, false, 43),
('Pastas', 'Fettuccine de Polo', 'Tagliatelle, chicken, mushrooms, cream sauce, parmesan', 60.00, '/images/menu/pastas/fettucini-polo.jpg', true, false, false, false, 44),
('Chinese Food', 'Szechuan Style Chicken', 'Chicken fillet, green pepper, carrot, baby corn, cauliflower, chili', 80.00, '/images/menu/chinese-food/beef-chop.jpg', true, true, false, false, 45),
('Chinese Food', 'Peking Style Chicken Sauce', 'Chicken fillet, chili, peanut, green pepper, onion, zucchini', 75.00, '/images/menu/chinese-food/chinese-beef.jpg', true, true, false, false, 46),
('Chinese Food', 'Sweet & Sour Fish', 'Fish, pineapple, tomatoes, onion, green pepper in sweet & sour sauce', 90.00, '/images/menu/chinese-food/chinese-chicken.jpg', true, false, false, false, 47),
('Chinese Food', 'Fish in Chili Sauce', 'Fish, onion, green pepper, chili', 85.00, '/images/menu/chinese-food/chinese-pork-sauce.jpg', true, true, false, false, 48),
('Chinese Food', 'Pork in Brown Chilli Sauce', 'Sliced pork, green pepper, onion, carrot, zucchini, peanut, chili', 65.00, '/images/menu/chinese-food/fish-chili-sauce.jpg', true, true, false, false, 49),
('Chinese Food', 'Beef Mongolian', 'Stir fry beef in spicy Mongolian sauce', 95.00, '/images/menu/chinese-food/perking-chicken-sauce.jpg', true, true, false, false, 50),
('Chinese Food', 'Beef Chop Suey', 'Stir fry beef, green beans, mushroom', 60.00, '/images/menu/chinese-food/sweet-sour-fish.jpg', true, false, false, false, 51),
('Indian Dishes', 'Vegetable Korma', 'Vegetable curry stew', 70.00, '/images/menu/indian-dishes/chicken-biyani.jpg', true, false, true, false, 52),
('Indian Dishes', 'Spicy Chicken Sauce', 'Boneless chicken in curry sauce', 80.00, '/images/menu/indian-dishes/chicken-tikka.jpg', true, true, false, false, 53),
('Indian Dishes', 'Chicken Tikka Masala', 'Basmati rice and chicken', 60.00, '/images/menu/indian-dishes/spicy-chicken.jpg', true, false, false, false, 54),
('Indian Dishes', 'Chicken Biryani', 'Indian chicken stew mixed with spices and herbs', 70.00, '/images/menu/indian-dishes/vegetable-korma.jpg', true, false, false, false, 55),
('Rice Dishes', 'Egg Fried Rice', 'Egg, spring onions in fried rice', 40.00, '/images/menu/rice-dishes/beef-rice.jpg', true, false, false, false, 56),
('Rice Dishes', 'Beef Fried Rice', 'Shredded beef in fried rice with egg on top', 60.00, '/images/menu/rice-dishes/chiken-fried-rice.jpg', true, false, false, false, 57),
('Rice Dishes', 'Chicken Fried Rice', 'Shredded chicken in fried rice with egg on top', 65.00, '/images/menu/rice-dishes/egg-fried-rice.jpg', true, false, false, false, 58),
('Rice Dishes', 'Zara Special Fried Rice', 'Shredded chicken and beef, vegetables with egg on top', 55.00, '/images/menu/rice-dishes/ghana.jpg', true, false, false, false, 59),
('Rice Dishes', 'Zara Special Jollof Rice', 'Shredded chicken and beef, vegetables with egg on top', 65.00, '/images/menu/rice-dishes/zara-special.jpg', true, false, false, false, 60),
('Ghanaian Specialities', 'Fully Loaded Waakye', 'Fish, beef, wele, boiled egg, gari, spaghetti, coleslaw and waakye', 75.00, '/images/menu/ghanaian-specialities/asakna-kotomire.jpg', true, false, false, false, 61),
('Ghanaian Specialities', 'Asanka Kontomire', 'Mashed kontomire, kobi, boiled egg, palm oil and sliced avocado', 95.00, '/images/menu/ghanaian-specialities/charcoal-tilapia.jpg', true, false, false, false, 62),
('Ghanaian Specialities', 'Palava Sauce with Ampesi (Tilapia)', 'Ampesi served with palava sauce and tilapia', 90.00, '/images/menu/ghanaian-specialities/fuly-loaded-waakye.jpg', true, false, false, false, 63),
('Ghanaian Specialities', 'Palava Sauce with Ampesi (Red Snapper)', 'Ampesi served with palava sauce and red snapper', 90.00, '/images/menu/ghanaian-specialities/grilled-cassava-fish.jpg', true, false, false, false, 64),
('Ghanaian Specialities', 'Palava Sauce with Ampesi (Cassava Fish)', 'Ampesi served with palava sauce and cassava fish', 85.00, '/images/menu/ghanaian-specialities/grilled-chicken.jpg', true, false, false, false, 65),
('Ghanaian Specialities', 'Palava Sauce with Ampesi (Smoked Tuna)', 'Ampesi served with palava sauce and smoked tuna', 100.00, '/images/menu/ghanaian-specialities/grilled-guinea-fowl.jpg', true, false, false, false, 66),
('Ghanaian Specialities', 'Palava Sauce with Ampesi (Smoked Salmon)', 'Ampesi served with palava sauce and smoked salmon', 105.00, '/images/menu/ghanaian-specialities/grilled-snapper.jpg', true, false, false, false, 67),
('From the Grill', 'Charcoal Grilled Tilapia', 'Served with a choice of banku, steamed rice, jollof rice or yam chips', 95.00, '/images/menu/from-the-grill/charcoal-tilapia.jpg', true, false, false, false, 68),
('From the Grill', 'Grilled Snapper', 'Served with a choice of banku, steamed rice, jollof rice or yam chips', 105.00, '/images/menu/from-the-grill/grilled-cassava-fish.jpg', true, false, false, false, 69),
('From the Grill', 'Whole Grilled Cassava Fish', 'Served with a choice of banku, steamed rice, jollof rice or yam chips', 75.00, '/images/menu/from-the-grill/grilled-chicken.jpg', true, false, false, false, 70),
('From the Grill', 'Grilled Guinea Fowl', 'Served with a choice of banku, steamed rice, jollof rice or yam chips', 105.00, '/images/menu/from-the-grill/grilled-guinea-fowl.jpg', true, false, false, false, 71),
('From the Grill', 'Charcoal Grilled Chicken', 'Served with a choice of banku, steamed rice, jollof rice or yam chips', 100.00, '/images/menu/from-the-grill/grilled-snapper.jpg', true, false, false, false, 72),
('Soups', 'Light Soup with Fresh Fufu', 'Choice of guinea fowl, tilapia, cassava fish, snapper, goat, chicken or smoked fish', 80.00, '/images/menu/soups/ebunubu-and-fufu.jpg', true, false, false, false, 73),
('Soups', 'Agushie Stew/Soup with Eba', 'Choice of guinea fowl, tilapia, snapper or goat', 75.00, '/images/menu/soups/egusi-and-eba.jpg', true, false, false, false, 74),
('Soups', 'Palmnut Soup with Fresh Fufu', 'Choice of guinea fowl, tilapia, cassava fish, snapper or goat', 55.00, '/images/menu/soups/fufu-and-palm.jpg', true, false, false, false, 75),
('Soups', 'Okro Stew/Soup with Banku', 'Choice of tilapia, cassava fish, snapper, goat, chicken or bone-in beef', 60.00, '/images/menu/soups/groundnut-and-riceball.jpg', true, false, false, false, 76),
('Soups', 'Ebunuabunu Soup with Fresh Fufu', 'Snail, dry fish, herrings, kobi, sliced okro and garden eggs', 70.00, '/images/menu/soups/light-soap.jpg', true, false, false, false, 77),
('Soups', 'Groundnut Soup with Rice Balls', 'Choice of guinea fowl, goat, tilapia, snapper, cassava fish, dry fish or bone-in beef', 45.00, '/images/menu/soups/okro-and-banku.jpg', true, false, false, false, 78),
('Soups', 'Red Red', 'Choice of goat, tilapia, snapper or chicken', 60.00, '/images/menu/soups/red-red.jpg', true, false, false, false, 79),
('Extra Dishes', 'Steamed Rice', 'A la carte side', 20.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 80),
('Extra Dishes', 'Jollof Rice', 'A la carte side', 20.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 81),
('Extra Dishes', 'Ga or Fante Kenkey', 'A la carte side', 15.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 82),
('Extra Dishes', 'Boiled or Fried Yam', 'A la carte side', 40.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 83),
('Extra Dishes', 'Banku, Akpele or Eba', 'A la carte side', 20.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 84),
('Extra Dishes', 'Fufu', 'A la carte side', 20.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 85),
('Extra Dishes', 'French Fries', 'A la carte side', 25.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 86),
('Extra Dishes', 'Yam Chips', 'A la carte side', 40.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 87),
('Extra Dishes', 'Goat 250g', 'A la carte protein', 15.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 88),
('Extra Dishes', 'Tilapia 400g', 'A la carte protein', 30.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 89),
('Extra Dishes', 'Beef 250g', 'A la carte protein', 30.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 90),
('Extra Dishes', 'Snapper 400g', 'A la carte protein', 40.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 91),
('Extra Dishes', 'Cassava Fish 400g', 'A la carte protein', 40.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 92),
('Extra Dishes', 'Grilled Chicken 250g', 'A la carte protein', 40.00, '/images/menu/extra-dishes/jollof-rice.jpg', true, false, false, false, 93),
('Desserts', 'Chocolate Pudding', 'Chocolate pudding served with chocolate ganache & vanilla ice cream', 25.00, '/images/menu/desserts/cakes-and-dessert.jpg', true, false, false, false, 94),
('Desserts', 'Fruit Salad', 'Assorted sliced fruits', 30.00, '/images/menu/desserts/chocolate-pudding.jpg', true, false, true, false, 95),
('Desserts', 'Cake and Desserts of the Day', 'Chef''s offering, choice of the day', 25.00, '/images/menu/desserts/fruit-salad.jpg', true, false, false, false, 96),
('Desserts', 'Ice Cream', 'Vanilla, chocolate, or strawberry', 40.00, '/images/menu/desserts/ice-cream.jpg', true, false, false, false, 97);

-- Feature a starter set of items in the homepage hero slideshow
update menu_items set is_featured_hero = true where name = 'Zara Special Jollof Rice';
update menu_items set is_featured_hero = true where name = 'Fully Loaded Waakye';
update menu_items set is_featured_hero = true where name = 'Charcoal Grilled Tilapia';
update menu_items set is_featured_hero = true where name = 'Red Red';
update menu_items set is_featured_hero = true where name = 'BBQ Chicken & Rib Combo';
update menu_items set is_featured_hero = true where name = 'Chocolate Pudding';