// lib/menuData.ts
// Shared menu category + item data, used by both the homepage (inline reveal)
// and the full /menu page, so there's a single source of truth.

export const MENU_CATEGORIES = [
  { id: 1, name: 'All Categories', emoji: '📋' },
  { id: 2, name: 'Healthy Breakfast', emoji: '🥗' },
  { id: 3, name: 'Hot Breakfast', emoji: '🍳' },
  { id: 4, name: 'On the Bakery', emoji: '🥐' },
  { id: 5, name: 'Appetisers', emoji: '🍤' },
  { id: 6, name: 'Salads', emoji: '🥬' },
  { id: 7, name: 'Light Meals', emoji: '🍴' },
  { id: 8, name: 'On the Grill', emoji: '🔥' },
  { id: 9, name: 'Pastas', emoji: '🍝' },
  { id: 10, name: 'Chinese Food', emoji: '🥢' },
  { id: 11, name: 'Indian Dishes', emoji: '🍛' },
  { id: 12, name: 'Rice Dishes', emoji: '🍚' },
  { id: 13, name: 'Ghanaian Specialities', emoji: '🍲' },
  { id: 14, name: 'From the Grill', emoji: '🐟' },
  { id: 15, name: 'Soups', emoji: '🍲' },
  { id: 16, name: 'Extra Dishes', emoji: '🍟' },
  { id: 17, name: 'Desserts', emoji: '🍰' },
]

export const SAMPLE_MENU_ITEMS = [
  {
    id: 1,
    category: 'Healthy Breakfast',
    name: 'Granola Bowl',
    price: 30.00,
    description: 'Muesli, plain yoghurt, assorted berries, chia seeds for garnish',
    image: '/images/menu/healthy-breakfast/cereak-bowl.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 2,
    category: 'Healthy Breakfast',
    name: 'Cereal Bowl',
    price: 25.00,
    description: 'Corn flakes, all bran flakes, oats porridge',
    image: '/images/menu/healthy-breakfast/fruit-salad.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 3,
    category: 'Healthy Breakfast',
    name: 'Fruit Salad',
    price: 35.00,
    description: 'Assorted sliced fruits',
    image: '/images/menu/healthy-breakfast/granola-bowl.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 4,
    category: 'Hot Breakfast',
    name: 'Zara Full Breakfast',
    price: 35.00,
    description: '2 fried eggs, bacon, grilled tomato, sausages, mushroom, hashbrown',
    image: '/images/menu/hot-breakfast/avocago-bacon-egg.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 5,
    category: 'Hot Breakfast',
    name: 'Avocado, Bacon & Egg Toast',
    price: 45.00,
    description: 'Health bread, smashed avocado, bacon, poached egg',
    image: '/images/menu/hot-breakfast/bacon-benedict.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 6,
    category: 'Hot Breakfast',
    name: 'Omelette',
    price: 40.00,
    description: 'Assorted fillings',
    image: '/images/menu/hot-breakfast/omlette.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 7,
    category: 'Hot Breakfast',
    name: 'Bacon Benedict',
    price: 35.00,
    description: 'English muffin, smoked salmon, poached egg, hollandaise sauce',
    image: '/images/menu/hot-breakfast/zara-full-breakfast1.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 8,
    category: 'On the Bakery',
    name: 'Assorted Muffins',
    price: 25.00,
    description: 'Chocolate, vanilla, berry',
    image: '/images/menu/on-the-bakery/assorted-muffins.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 9,
    category: 'On the Bakery',
    name: 'Pancakes',
    price: 15.00,
    description: 'Garnished with syrup and whipped cream',
    image: '/images/menu/on-the-bakery/croissant.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 10,
    category: 'On the Bakery',
    name: 'Waffles',
    price: 20.00,
    description: 'Garnished with chocolate sauce and honey',
    image: '/images/menu/on-the-bakery/pan-cake.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 11,
    category: 'On the Bakery',
    name: 'Scones',
    price: 15.00,
    description: 'Served with a side of jam and cheese',
    image: '/images/menu/on-the-bakery/scones.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 12,
    category: 'On the Bakery',
    name: 'Croissants',
    price: 15.00,
    description: 'Plain, cheese & ham, or cheese & tomato',
    image: '/images/menu/on-the-bakery/waffles.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 13,
    category: 'Appetisers',
    name: 'Fried Calamari',
    price: 45.00,
    description: 'With aioli & lemon herb',
    image: '/images/menu/appetisers/chicken-wings.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 14,
    category: 'Appetisers',
    name: 'Chicken Wings',
    price: 55.00,
    description: 'Soy glazed crispy chicken wings, topped with sesame seeds & coriander',
    image: '/images/menu/appetisers/chicken-wings1.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 15,
    category: 'Appetisers',
    name: 'Prawns',
    price: 35.00,
    description: 'Flash fried in chili, garlic, butter, lemon & parsley',
    image: '/images/menu/appetisers/fried-calamari.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 16,
    category: 'Appetisers',
    name: 'Kelewele',
    price: 35.00,
    description: 'Spicy fried plantain',
    image: '/images/menu/appetisers/guinea-fowl.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 17,
    category: 'Appetisers',
    name: 'Grilled Spicy Guinea Fowl',
    price: 50.00,
    description: 'Spring onions, red chili, kebab powder',
    image: '/images/menu/appetisers/kelewele.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 18,
    category: 'Appetisers',
    name: 'Spicy Pork Ribs',
    price: 60.00,
    description: 'Spring onions, red chili, kebab powder',
    image: '/images/menu/appetisers/prawns.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 19,
    category: 'Appetisers',
    name: 'Vegetable Spring Rolls',
    price: 45.00,
    description: 'Onions, cabbage, carrots, chef\'s special spice',
    image: '/images/menu/appetisers/chicken-wings.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 20,
    category: 'Salads',
    name: 'Asian Calamari Salad',
    price: 35.00,
    description: 'Grilled or fried calamari, pickled ginger, tomato, avocado, cucumber, greens & spring onion with a soy miso dressing',
    image: '/images/menu/salads/asian-salad.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 21,
    category: 'Salads',
    name: 'Caesar Salad',
    price: 45.00,
    description: 'Crisp romaine lettuce with creamy Caesar dressing, anchovies, grilled chicken, bacon, Parmesan cheese',
    image: '/images/menu/salads/avacado-salad.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 22,
    category: 'Salads',
    name: 'Avocado Salad',
    price: 25.00,
    description: 'Lettuce, cucumber, carrot, tomato, avocado, onions, chopped parsley, chopped chilli, honey, olive oil',
    image: '/images/menu/salads/ceaser-salad.jpg',
    isSpicy: true,
    isVegetarian: true,
  },
  {
    id: 23,
    category: 'Salads',
    name: 'Green Salad',
    price: 40.00,
    description: 'Lettuce, green pepper, cucumber, spring onion, green beans, green olives, olive oil',
    image: '/images/menu/salads/green-salad.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 24,
    category: 'Salads',
    name: 'Zara Ghanaian Salad',
    price: 30.00,
    description: 'Lettuce, cabbage, tuna flakes, baked beans, tomatoes, onion, egg, chicken, chef\'s special sauce',
    image: '/images/menu/salads/zara-salad.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 25,
    category: 'Light Meals',
    name: 'Club Sandwich',
    price: 35.00,
    description: 'Brown or white toast, lettuce, tomato, cheese, ham, sauce -- served with fries or salad',
    image: '/images/menu/light-meals/bacon-avo.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 26,
    category: 'Light Meals',
    name: 'Zara Chic',
    price: 35.00,
    description: 'Brown or white toast, lettuce, chicken mayo, cheese, sauce -- served with fries or salad',
    image: '/images/menu/light-meals/beef-wrap.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 27,
    category: 'Light Meals',
    name: 'Missy Tuna',
    price: 40.00,
    description: 'Brown or white toast, lettuce, tuna, cheese, sauce -- served with fries or salad',
    image: '/images/menu/light-meals/boss-lady.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 28,
    category: 'Light Meals',
    name: 'Boss Lady',
    price: 50.00,
    description: 'Brown or white toast, lettuce, fried egg, bacon, tomato, cheese, sauce -- served with fries or salad',
    image: '/images/menu/light-meals/chicken-burger.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 29,
    category: 'Light Meals',
    name: 'Bacon Avo',
    price: 35.00,
    description: 'Baguette bread, bacon, avocado, cucumber, arugula, baby spinach, radish, sunflower tomatoes, creamy cheese',
    image: '/images/menu/light-meals/chicken-wrap.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 30,
    category: 'Light Meals',
    name: 'Chicken Wrap',
    price: 45.00,
    description: 'Tortilla, lettuce, green pepper, tomato, shredded chicken, sauce -- served with fries or salad',
    image: '/images/menu/light-meals/coument-beef.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 31,
    category: 'Light Meals',
    name: 'Beef Wrap',
    price: 45.00,
    description: 'Tortilla, lettuce, green pepper, caramelized onion, tomato, shredded beef, sauce -- served with fries or salad',
    image: '/images/menu/light-meals/miss-tuna.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 32,
    category: 'Light Meals',
    name: 'Chicken Burger',
    price: 40.00,
    description: 'Bun, lettuce, chicken fillet, gherkins, tomato, caramelized onion, cheese -- served with fries or salad',
    image: '/images/menu/light-meals/sandwitch.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 33,
    category: 'Light Meals',
    name: 'Gourmet Beef Burger',
    price: 45.00,
    description: 'Bun, lettuce, beef patty, gherkins, tomato, crispy bacon, caramelized onion, cheese, sauce -- served with fries or salad',
    image: '/images/menu/light-meals/zara-chic.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 34,
    category: 'On the Grill',
    name: 'Beef Tenderloin 250g',
    price: 95.00,
    description: 'Served with a side of salad, mediterranean vegetables, mashed potatoes or French fries',
    image: '/images/menu/on-the-grill/bbq-chicken.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 35,
    category: 'On the Grill',
    name: 'Surf & Turf',
    price: 95.00,
    description: '200g beef steak, 5 queen prawns, served with French fries',
    image: '/images/menu/on-the-grill/beef-tenderliom.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 36,
    category: 'On the Grill',
    name: 'BBQ Chicken & Rib Combo',
    price: 105.00,
    description: 'Quarter leg chicken, 200g pork ribs, served with French fries',
    image: '/images/menu/on-the-grill/grilled-salmon.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 37,
    category: 'On the Grill',
    name: 'Lamb Chops 250g',
    price: 140.00,
    description: 'Served with a side of salad, mediterranean vegetables, mash potatoes or French fries',
    image: '/images/menu/on-the-grill/lamb-chop.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 38,
    category: 'On the Grill',
    name: 'Grilled Salmon',
    price: 120.00,
    description: 'Grilled salmon in teriyaki sauce, served with mashed potatoes or mediterranean vegetables',
    image: '/images/menu/on-the-grill/surf-turf.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 39,
    category: 'Pastas',
    name: 'Grilled Creamy Chicken Pesto Pasta',
    price: 65.00,
    description: 'Grilled chicken, mushrooms in a creamy basil pesto sauce, penne pasta and Grana Padano shavings',
    image: '/images/menu/pastas/fettucini-polo.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 40,
    category: 'Pastas',
    name: 'Seafood Pasta',
    price: 75.00,
    description: 'Hake, mussels, prawns and calamari in a creamy prawn and lemongrass sauce, served with fettuccine',
    image: '/images/menu/pastas/grilled-creamy.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 41,
    category: 'Pastas',
    name: 'Mushroom Pasta (V)',
    price: 70.00,
    description: 'Medley of mixed mushrooms gently simmered in a creamy Parmesan sauce, served with penne pasta',
    image: '/images/menu/pastas/mac-cheease.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 42,
    category: 'Pastas',
    name: 'Mac & Cheese',
    price: 65.00,
    description: 'Creamy cheese sauce, penne pasta and melted cheddar cheese',
    image: '/images/menu/pastas/mushroom.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 43,
    category: 'Pastas',
    name: 'Spaghetti Bolognaise',
    price: 80.00,
    description: 'Napolitano sauce, beef mince and spaghetti pasta',
    image: '/images/menu/pastas/penne-arabtiana.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 44,
    category: 'Pastas',
    name: 'Penne Arrabbiata',
    price: 75.00,
    description: 'Spicy pomodoro, olives, parmesan cheese',
    image: '/images/menu/pastas/sea-food.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 45,
    category: 'Pastas',
    name: 'Fettuccine de Polo',
    price: 60.00,
    description: 'Tagliatelle, chicken, mushrooms, cream sauce, parmesan',
    image: '/images/menu/pastas/fettucini-polo.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 46,
    category: 'Chinese Food',
    name: 'Szechuan Style Chicken',
    price: 80.00,
    description: 'Chicken fillet, green pepper, carrot, baby corn, cauliflower, chili',
    image: '/images/menu/chinese-food/beef-chop.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 47,
    category: 'Chinese Food',
    name: 'Peking Style Chicken Sauce',
    price: 75.00,
    description: 'Chicken fillet, chili, peanut, green pepper, onion, zucchini',
    image: '/images/menu/chinese-food/chinese-beef.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 48,
    category: 'Chinese Food',
    name: 'Sweet & Sour Fish',
    price: 90.00,
    description: 'Fish, pineapple, tomatoes, onion, green pepper in sweet & sour sauce',
    image: '/images/menu/chinese-food/chinese-chicken.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 49,
    category: 'Chinese Food',
    name: 'Fish in Chili Sauce',
    price: 85.00,
    description: 'Fish, onion, green pepper, chili',
    image: '/images/menu/chinese-food/chinese-pork-sauce.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 50,
    category: 'Chinese Food',
    name: 'Pork in Brown Chilli Sauce',
    price: 65.00,
    description: 'Sliced pork, green pepper, onion, carrot, zucchini, peanut, chili',
    image: '/images/menu/chinese-food/fish-chili-sauce.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 51,
    category: 'Chinese Food',
    name: 'Beef Mongolian',
    price: 95.00,
    description: 'Stir fry beef in spicy Mongolian sauce',
    image: '/images/menu/chinese-food/perking-chicken-sauce.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 52,
    category: 'Chinese Food',
    name: 'Beef Chop Suey',
    price: 60.00,
    description: 'Stir fry beef, green beans, mushroom',
    image: '/images/menu/chinese-food/sweet-sour-fish.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 53,
    category: 'Indian Dishes',
    name: 'Vegetable Korma',
    price: 70.00,
    description: 'Vegetable curry stew',
    image: '/images/menu/indian-dishes/chicken-biyani.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 54,
    category: 'Indian Dishes',
    name: 'Spicy Chicken Sauce',
    price: 80.00,
    description: 'Boneless chicken in curry sauce',
    image: '/images/menu/indian-dishes/chicken-tikka.jpg',
    isSpicy: true,
    isVegetarian: false,
  },
  {
    id: 55,
    category: 'Indian Dishes',
    name: 'Chicken Tikka Masala',
    price: 60.00,
    description: 'Basmati rice and chicken',
    image: '/images/menu/indian-dishes/spicy-chicken.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 56,
    category: 'Indian Dishes',
    name: 'Chicken Biryani',
    price: 70.00,
    description: 'Indian chicken stew mixed with spices and herbs',
    image: '/images/menu/indian-dishes/vegetable-korma.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 57,
    category: 'Rice Dishes',
    name: 'Egg Fried Rice',
    price: 40.00,
    description: 'Egg, spring onions in fried rice',
    image: '/images/menu/rice-dishes/beef-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 58,
    category: 'Rice Dishes',
    name: 'Beef Fried Rice',
    price: 60.00,
    description: 'Shredded beef in fried rice with egg on top',
    image: '/images/menu/rice-dishes/chiken-fried-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 59,
    category: 'Rice Dishes',
    name: 'Chicken Fried Rice',
    price: 65.00,
    description: 'Shredded chicken in fried rice with egg on top',
    image: '/images/menu/rice-dishes/egg-fried-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 60,
    category: 'Rice Dishes',
    name: 'Zara Special Fried Rice',
    price: 55.00,
    description: 'Shredded chicken and beef, vegetables with egg on top',
    image: '/images/menu/rice-dishes/ghana.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 61,
    category: 'Rice Dishes',
    name: 'Zara Special Jollof Rice',
    price: 65.00,
    description: 'Shredded chicken and beef, vegetables with egg on top',
    image: '/images/menu/rice-dishes/zara-special.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 62,
    category: 'Ghanaian Specialities',
    name: 'Fully Loaded Waakye',
    price: 75.00,
    description: 'Fish, beef, wele, boiled egg, gari, spaghetti, coleslaw and waakye',
    image: '/images/menu/ghanaian-specialities/asakna-kotomire.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 63,
    category: 'Ghanaian Specialities',
    name: 'Asanka Kontomire',
    price: 95.00,
    description: 'Mashed kontomire, kobi, boiled egg, palm oil and sliced avocado',
    image: '/images/menu/ghanaian-specialities/charcoal-tilapia.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 64,
    category: 'Ghanaian Specialities',
    name: 'Palava Sauce with Ampesi (Tilapia)',
    price: 90.00,
    description: 'Ampesi served with palava sauce and tilapia',
    image: '/images/menu/ghanaian-specialities/fuly-loaded-waakye.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 65,
    category: 'Ghanaian Specialities',
    name: 'Palava Sauce with Ampesi (Red Snapper)',
    price: 90.00,
    description: 'Ampesi served with palava sauce and red snapper',
    image: '/images/menu/ghanaian-specialities/grilled-cassava-fish.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 66,
    category: 'Ghanaian Specialities',
    name: 'Palava Sauce with Ampesi (Cassava Fish)',
    price: 85.00,
    description: 'Ampesi served with palava sauce and cassava fish',
    image: '/images/menu/ghanaian-specialities/grilled-chicken.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 67,
    category: 'Ghanaian Specialities',
    name: 'Palava Sauce with Ampesi (Smoked Tuna)',
    price: 100.00,
    description: 'Ampesi served with palava sauce and smoked tuna',
    image: '/images/menu/ghanaian-specialities/grilled-guinea-fowl.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 68,
    category: 'Ghanaian Specialities',
    name: 'Palava Sauce with Ampesi (Smoked Salmon)',
    price: 105.00,
    description: 'Ampesi served with palava sauce and smoked salmon',
    image: '/images/menu/ghanaian-specialities/grilled-snapper.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 69,
    category: 'From the Grill',
    name: 'Charcoal Grilled Tilapia',
    price: 95.00,
    description: 'Served with a choice of banku, steamed rice, jollof rice or yam chips',
    image: '/images/menu/from-the-grill/charcoal-tilapia.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 70,
    category: 'From the Grill',
    name: 'Grilled Snapper',
    price: 105.00,
    description: 'Served with a choice of banku, steamed rice, jollof rice or yam chips',
    image: '/images/menu/from-the-grill/grilled-cassava-fish.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 71,
    category: 'From the Grill',
    name: 'Whole Grilled Cassava Fish',
    price: 75.00,
    description: 'Served with a choice of banku, steamed rice, jollof rice or yam chips',
    image: '/images/menu/from-the-grill/grilled-chicken.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 72,
    category: 'From the Grill',
    name: 'Grilled Guinea Fowl',
    price: 105.00,
    description: 'Served with a choice of banku, steamed rice, jollof rice or yam chips',
    image: '/images/menu/from-the-grill/grilled-guinea-fowl.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 73,
    category: 'From the Grill',
    name: 'Charcoal Grilled Chicken',
    price: 100.00,
    description: 'Served with a choice of banku, steamed rice, jollof rice or yam chips',
    image: '/images/menu/from-the-grill/grilled-snapper.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 74,
    category: 'Soups',
    name: 'Light Soup with Fresh Fufu',
    price: 80.00,
    description: 'Choice of guinea fowl, tilapia, cassava fish, snapper, goat, chicken or smoked fish',
    image: '/images/menu/soups/ebunubu-and-fufu.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 75,
    category: 'Soups',
    name: 'Agushie Stew/Soup with Eba',
    price: 75.00,
    description: 'Choice of guinea fowl, tilapia, snapper or goat',
    image: '/images/menu/soups/egusi-and-eba.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 76,
    category: 'Soups',
    name: 'Palmnut Soup with Fresh Fufu',
    price: 55.00,
    description: 'Choice of guinea fowl, tilapia, cassava fish, snapper or goat',
    image: '/images/menu/soups/fufu-and-palm.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 77,
    category: 'Soups',
    name: 'Okro Stew/Soup with Banku',
    price: 60.00,
    description: 'Choice of tilapia, cassava fish, snapper, goat, chicken or bone-in beef',
    image: '/images/menu/soups/groundnut-and-riceball.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 78,
    category: 'Soups',
    name: 'Ebunuabunu Soup with Fresh Fufu',
    price: 70.00,
    description: 'Snail, dry fish, herrings, kobi, sliced okro and garden eggs',
    image: '/images/menu/soups/light-soap.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 79,
    category: 'Soups',
    name: 'Groundnut Soup with Rice Balls',
    price: 45.00,
    description: 'Choice of guinea fowl, goat, tilapia, snapper, cassava fish, dry fish or bone-in beef',
    image: '/images/menu/soups/okro-and-banku.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 80,
    category: 'Soups',
    name: 'Red Red',
    price: 60.00,
    description: 'Choice of goat, tilapia, snapper or chicken',
    image: '/images/menu/soups/red-red.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 81,
    category: 'Extra Dishes',
    name: 'Steamed Rice',
    price: 20.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 82,
    category: 'Extra Dishes',
    name: 'Jollof Rice',
    price: 20.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 83,
    category: 'Extra Dishes',
    name: 'Ga or Fante Kenkey',
    price: 15.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 84,
    category: 'Extra Dishes',
    name: 'Boiled or Fried Yam',
    price: 40.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 85,
    category: 'Extra Dishes',
    name: 'Banku, Akpele or Eba',
    price: 20.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 86,
    category: 'Extra Dishes',
    name: 'Fufu',
    price: 20.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 87,
    category: 'Extra Dishes',
    name: 'French Fries',
    price: 25.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 88,
    category: 'Extra Dishes',
    name: 'Yam Chips',
    price: 40.00,
    description: 'A la carte side',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 89,
    category: 'Extra Dishes',
    name: 'Goat 250g',
    price: 15.00,
    description: 'A la carte protein',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 90,
    category: 'Extra Dishes',
    name: 'Tilapia 400g',
    price: 30.00,
    description: 'A la carte protein',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 91,
    category: 'Extra Dishes',
    name: 'Beef 250g',
    price: 30.00,
    description: 'A la carte protein',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 92,
    category: 'Extra Dishes',
    name: 'Snapper 400g',
    price: 40.00,
    description: 'A la carte protein',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 93,
    category: 'Extra Dishes',
    name: 'Cassava Fish 400g',
    price: 40.00,
    description: 'A la carte protein',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 94,
    category: 'Extra Dishes',
    name: 'Grilled Chicken 250g',
    price: 40.00,
    description: 'A la carte protein',
    image: '/images/menu/extra-dishes/jollof-rice.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 95,
    category: 'Desserts',
    name: 'Chocolate Pudding',
    price: 25.00,
    description: 'Chocolate pudding served with chocolate ganache & vanilla ice cream',
    image: '/images/menu/desserts/cakes-and-dessert.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 96,
    category: 'Desserts',
    name: 'Fruit Salad',
    price: 30.00,
    description: 'Assorted sliced fruits',
    image: '/images/menu/desserts/chocolate-pudding.jpg',
    isSpicy: false,
    isVegetarian: true,
  },
  {
    id: 97,
    category: 'Desserts',
    name: 'Cake and Desserts of the Day',
    price: 25.00,
    description: 'Chef\'s offering, choice of the day',
    image: '/images/menu/desserts/fruit-salad.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
  {
    id: 98,
    category: 'Desserts',
    name: 'Ice Cream',
    price: 40.00,
    description: 'Vanilla, chocolate, or strawberry',
    image: '/images/menu/desserts/ice-cream.jpg',
    isSpicy: false,
    isVegetarian: false,
  },
]
